contract:
  search:
    - 行政人员
    - 项目经理
    - 销售人员
    - 技术支持
    - 系统开发
    - 部门主管
    - 业务拓展
    - 总经理
    - 管理员
  add:
    - 行政人员
    - 管理员
  update1:
    - 行政人员
    - 管理员
  delete:
    - 行政人员
    - 管理员
order:
  search:
    - 行政人员
    - 管理员
  add:
    - 行政人员
    - 管理员
  update:
    - 行政人员
    - 管理员
  delete:
    - 行政人员
    - 管理员
user:
  add:
    - 管理员
  delete:
    - 管理员
customer:
  add:
    - 行政人员
    - 管理员
  update1:
    - 行政人员
    - 项目经理
    - 业务拓展
    - 管理员
  delete:
    - 行政人员
    - 管理员
  add_group:
    - 项目经理
    - 业务拓展
    - 管理员
vendor:
  add:
    - 管理员
    - 项目经理
    - 行政人员
    - 业务拓展
  delete:
    - 管理员
    - 项目经理
    - 行政人员
    - 业务拓展
customer_group:
  add:
    - 管理员
    - 项目经理
    - 业务拓展
  delete:
    - 管理员
    - 项目经理
    - 业务拓展
mail_send:
  - 管理员
  - 项目经理
  - 业务拓展
send_record :
  - 项目经理
  - 销售人员
  - 技术支持
  - 部门主管
  - 业务拓展
  - 总经理
  - 管理员
license_apply:
  - 项目经理
  - 技术支持
  - 部门主管
  - 业务拓展
  - 管理员